version: "3"
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: dfirtrack
            POSTGRES_USER: ${pg_user}
            POSTGRES_PASSWORD: ${pg_password}
        volumes:
            - db-data:/var/lib/postgresql/data

    dfirtrack:
        image: dfirtrack/dfirtrack:latest
        environment:
            - DB_HOST=db
            - DB_USER=${pg_user}
            - DB_PASSWORD=${pg_password}
            - FQDN=${fqdn}
            - SECRET_KEY=${django_secret_key}
            - DISABLE_HTTPS=false

        ports:
            - 80:80
            - 443:443
        depends_on:
            - db

volumes:
    db-data:
